// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxqebhbscblkbfhljfdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94cWViaGJzY2Jsa2JmaGxqZmRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5OTA5OTgsImV4cCI6MjA4MTU2Njk5OH0.lEd6sRl291A_rSQiZDcQHDxTSOGv3GoLtoMT6xmvdVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});